### ISSUE TITLE
Release version 0.0.2 with changes from #243 as they will make plugin development much easier

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/Morganey#244]

**Comment by rexim** [comment]
1. It's up to the Project Leader to decide how to number the next stable version . Since we follow http://semver.org/ the next version won't be called 0.0.2 if it's gonna include #242.
2. Please don't put issue numbers in the title of the issue. They are not clickable and and not automatically linked.
3. Please don't create issue for including particular features to the next stable release. It clutters the issue tracker. I'd appreciate if you simply ask to include features to the next stable releases in the corresponding tickets.

I will include #242 to the next stable release once I plan it properly.

Thanks.

**Comment by 06needhamt** [comment]
Ok no problem

**Comment by rexim** [comment]
@06needhamt please refer to https://github.com/morganey-lang/Morganey/milestone/1 for the next release. If you want any issues to be included there simply tell me that in the issues themselves and I'll include them to the milestone. :)
