### ISSUE TITLE
Multiline expressions

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#275]
I wanna be able to implement `takeWhile` function like this:

``` haskell
takeWhile := Y (\rec.p.xs.
  (isnil xs)
  []
  ((p (head xs))
   (cons (head xs) (rec p (tail xs)))
   []))
```

Instead of this:

``` haskell
takeWhile := Y (\rec.p.xs. (isnil xs) [] ((p (head xs)) (cons (head xs) (rec p (tail xs))) []))
```

**Comment by keddelzz** [comment]
I've looked into why multi-line expressions are not working right now:

#### The current situation

At the moment white-space (except line-breaks) is handled by the parser-combinator library. The parser disallows the usage of line-breaks in applications and it requires at least one line-break between the bindings. To allow multi-line expression line-breaks must be allowed between any term. The problem with that is described in the next section.

## 

#### The general problem

Applications should contain **any** whitespace between the terms. Because of that, the parser wouldn't be able to distinguish terms on the right hand side of an binding and the next defined binding-name.

Consider the definitions:

``` haskell
takeWhile := Y (\rec.p.xs.
  (isnil xs)
  []
  ((p (head xs))
   (cons (head xs) (rec p (tail xs)))
   []))

test :=
    succ (
        plus 2 5
    )
```

In this example the parser won't be able to distinguish between the the right-hand side of the binding `takeWhile` and the binding name `test` and thus try to parse the following application:

```
( <rhs of takeWhile>   <test (binding name> )
```

Parsing this application will obviously fail, because the parser won't expect the `:=`.

## 

#### Proposed solutions

##### Mark the start/end of a binding-definition explicitly
- Introducing a keyword for bindings (e.g. `def`). It will explicitly mark the start of a binding.

or
- Introducing an explicit end of a definition (e.g. a semicolon `;`).

##### Rewrite the parser
- Rewrite the parser to handle whitespace by hand. This might require introducing a tokenizer (which is also possible with scala-parser-combinators: [scanners with parser-combinators](https://github.com/scala/scala-parser-combinators/blob/1.0.x/shared/src/main/scala/scala/util/parsing/combinator/lexical/Scanners.scala) and [token parsers](https://github.com/scala/scala-parser-combinators/blob/1.0.x/shared/src/main/scala/scala/util/parsing/combinator/syntactical/TokenParsers.scala)). Using a token-parser, white-space-tokens can be treated specially.

**Comment by keddelzz** [comment]
I don't want to push the decision in any direction, but I tried using the explicit keyword `def` for the definition of the bindings locally. The changes that i did, were extremely easy and work completely as desired.

Excerpt from a test mgn-file:

``` haskell
// omitting some definitions

def test :=
    succ (
        plus 2 5
    )

def test2 :=
    plus
    (mult test test)
    (mult test test)

def takeWhile := Y (\rec.p.xs.
  (isnil xs)
  []
  ((p (head xs))
   (cons (head xs) (rec p (tail xs)))
   []))
```

**Comment by BjoernLoetters** [comment]
That's a nice idea. I believe that line breaks are absolutely necessary.

I would prefer to mark the bindings with a keyword instead of appending a semicolon (but that's a matter of taste). A clear advantage of a keyword would be the possibility of syntax highlighting (I've never seen an editor with syntax highlighting for semicolons). 

The use of the keyword `def` would allow to use the classic `let ... in ...` for private bindings (so one can clearly distinguish between private and public bindings).

I hope this feature will be implemented, especially because I've started to write a turing machine in Morganey. :-)

**Comment by rexim** [comment]
@keddelzz I briefly read your proposal. Thank you very much for looking into that! A bit later I'm gonna read it carefully and answer something. In the meantime could you please show the changes you did in https://github.com/morganey-lang/Morganey/issues/275#issuecomment-258676245 ? Maybe in a form of PR that closes this issue? Thanks!

**Comment by keddelzz** [comment]
Yes, of course i will push it in a few minutes, I'm gonna clean up the code a bit.

**Comment by keddelzz** [comment]
@rexim You can find a PR which shows the changes I did in #295.

**Comment by rexim** [comment]
@keddelzz cool! Thank you very much for spending your time on this! I'll try to find some time to look into this tomorrow. Thanks!

**Comment by rexim** [comment]
@keddelzz ok, I read the results of your research and I agree with the solution. Thank you very much! Let me review the PR...
