### ISSUE TITLE
Make our purely functional interpretation more readable

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#30]
Basically, get rid of that: https://github.com/rexim/Morganey/blob/b12bc01238754f6cbef61248a7e125ce269687a6/src/main/scala/me/rexim/morganey/MorganeyInterpreter.scala#L28

cc @ForNeVeR

**Comment by rexim** [comment]
Btw, in the official docs about Streams my approach is demonstrated as a first example %) http://www.scala-lang.org/api/current/#scala.collection.immutable.Stream

**Comment by ForNeVeR** [comment]
Wow, but such code definitely wasn't compiling for us.

**Comment by rexim** [comment]
Yeah, that's strange. I'll try to investigate that later today.

**Comment by rexim** [comment]
Here are some of my observations. Assume we have this classical example of corecursion

`val fibs: Stream[Int] = 0 #:: 1 #:: fibs.zip(fibs.tail).map { n => n._1 + n._2 }`

which lazily generates fibonacci sequence.

If we put it outside of any method like that:

```
object Main extends App {
  val fibs: Stream[Int] = 0 #:: 1 #:: fibs.zip(fibs.tail).map { n => n._1 + n._2 }
}
```

everything compiles and works perfectly. But if you put it inside of any method like that:

```
object Main extends App {
  def f = {
    ...
    val fibs: Stream[Int] = 0 #:: 1 #:: fibs.zip(fibs.tail).map { n => n._1 + n._2 }
    ...
  }
}
```

the Scala compiler complains about `forward reference extends over definition of value fibs`. But if in the second case you replace `val` with `lazy val` everything works and compiles perfectly.

I tried this approach for our corecursive thingy and it seems to be working: https://github.com/rexim/Morganey/blob/0e8e774c758a98eb81d81ef220cf842f808b9150/src/main/scala/me/rexim/morganey/MorganeyInterpreter.scala#L30

**Comment by ForNeVeR** [comment]
Aha, well. I wasn't aware that it's called corecursion.

I think I have an explanation about that behavior.

When you write this expression as a class field, it will just reference the class field in the lambda body, and everything will be okay (in fact, it does reference `this` and not the field itself, because there is no such thing as "field reference" in Java).

But being written as a local variable, it creates a problem for the compiler: it should immediately place something into a variable, but the lambda should reference the parent "variable" itself. I think that requires more complex transformations than the ordinary closure generation, and that's the reason compiler (and not only the Scala compiler, but, for example, C# compiler also, and I think the same will be right for Java) explicitly forbids that declaration.

Well, at last, I think that using `lazy val` should be okay here.

**Comment by rexim** [comment]
@ForNeVeR hm... this is interesting! Thanks for the explanation!
