### ISSUE TITLE
Get rid of reflective access of structural type member warning

### ISSUE THREAD

**Issue by rexim** [morganey-lang/Morganey#44]
Currently during compilation we see the following warning:

```
[warn] /home/rexim/Programming/codingteam/morganey/src/main/scala/me/rexim/morganey/Main.scala:50: reflective access of structural type member method setCancel should be enabled
[warn] by making the implicit value scala.language.reflectiveCalls visible.
[warn] This can be achieved by adding the import clause 'import scala.language.reflectiveCalls'
[warn] or by setting the compiler option -language:reflectiveCalls.
[warn] See the Scala docs for value scala.language.reflectiveCalls for a discussion
[warn] why the feature should be explicitly enabled.
[warn]         replSignalHandler.setCancel(cancel)
[warn]                           ^
[warn] one warning found
```

It was introduced by #40. We need to get rid of this warning.

**Comment by ForNeVeR** [comment]
What the hell.

**Comment by rexim** [comment]
@ForNeVeR, I was just raping the source code of Morganey recently. No big deal.

**Comment by ForNeVeR** [comment]
Wow, I got that. If you introduce _new_ (i.e. not inherited) public members to the anonymous types generated by `new ... { }` expression, the resulting type (as I understood) will not be used anywhere outside of a `new { }` expression. So `scalac` knows that the type has these members, but falls back to reflection if you want to call them, because it have no permitted way of expressing these members without mentioning an "anonymous" type.

What a great mindfuck, I like that!

**Comment by rexim** [comment]
@ForNeVeR Hah! That's cool! Thank you! I didn't even think about it. :)

**Comment by rexim** [comment]
Anyway, I know how to get rid of this. Already planned for today's stream
